# vim: ft=dosini
[tool.isort]
profile = "black"
# multi_line_output = 3
# include_trailing_comma = true
# force_grid_wrap = 0
# use_parentheses = true
# ensure_newline_before_comments = false
# line_length = 10

[tool.black]
line-length = 121
